version: '0.1'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/terraform
    working_dir: /terraform
    environment:
      - TF_VAR_api_token="$(shell cat .mdp)"
    entrypoint: ["/bin/terraform"]
